global using System;
global using System.Collections.Generic;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Media;
global using WinForms = System.Windows.Forms;
global using WPFBrush = System.Windows.Media.Brush;
global using WPFBrushes = System.Windows.Media.Brushes;
global using DrawingBrush = System.Drawing.Brush;
global using Microsoft.Extensions.DependencyInjection;
global using NLog; 