name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Clean Solution
      run: |
        dotnet clean
        dotnet nuget locals all --clear
      
    - name: Configure NuGet Sources
      run: |
        dotnet nuget remove source nuget.org
        dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
        
    - name: Restore dependencies
      run: dotnet restore --force
      
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=false
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true
      
    - name: Create LICENSE file
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "MIT License" > LICENSE
        echo "" >> LICENSE
        echo "Copyright (c) 2024 TelegramAutomation" >> LICENSE
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/Release/net8.0-windows/win-x64/publish/TelegramAutomation.exe
          LICENSE
          README.md
          CHANGELOG.md
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}