name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Clear NuGet Cache
      run: |
        dotnet nuget locals all --clear
        
    - name: Configure NuGet
      run: |
        dotnet nuget list source
        dotnet nuget remove source nuget.org || echo "Source not found"
        dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org || echo "Source already exists"
        
    - name: Restore dependencies
      run: |
        dotnet restore --force --source https://api.nuget.org/v3/index.json
      
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=false
      
    - name: Test ChromeDriver
      run: |
        $driverPath = "bin\Release\net6.0-windows\chromedriver.exe"
        Write-Host "检查 ChromeDriver 是否存在: $driverPath"
        if (Test-Path $driverPath) {
          Write-Host "ChromeDriver 文件存在"
          $version = (Get-Item $driverPath).VersionInfo.FileVersion
          Write-Host "ChromeDriver 版本: $version"
          
          # 尝试启动 ChromeDriver
          try {
            $process = Start-Process -FilePath $driverPath -ArgumentList "--version" -NoNewWindow -PassThru -Wait
            if ($process.ExitCode -eq 0) {
              Write-Host "ChromeDriver 启动测试成功"
            } else {
              Write-Error "ChromeDriver 启动测试失败"
              exit 1
            }
          } catch {
            Write-Error "ChromeDriver 启动失败: $_"
            exit 1
          }
        } else {
          Write-Error "ChromeDriver 文件不存在"
          exit 1
        }

    - name: Test Login Module
      run: |
        Write-Host "开始测试登录模块..."
        
        # 测试手机号码输入
        Write-Host "测试手机号码输入功能"
        $testPhones = @(
          "+1234567890",
          "+861234567890",
          "12345678901"
        )
        
        foreach ($phone in $testPhones) {
          Write-Host "测试手机号: $phone"
          try {
            # 使用 PowerShell 的 Out-File 来测试输入
            $testFile = "phone_input_test.txt"
            $phone | Out-File -FilePath $testFile
            
            # 读取并验证
            $content = Get-Content -Path $testFile -Raw
            $content = $content.TrimEnd()  # 移除末尾的换行符
            
            if ($content -eq $phone) {
              Write-Host "手机号输入测试成功: $phone" -ForegroundColor Green
            } else {
              Write-Host "手机号输入测试失败: 期望 '$phone', 实际 '$content'" -ForegroundColor Red
              Write-Host "长度对比: 期望 $($phone.Length), 实际 $($content.Length)" -ForegroundColor Yellow
            }
            
            # 清理
            Remove-Item $testFile -ErrorAction SilentlyContinue
          } catch {
            Write-Host "手机号输入测试出错: $_" -ForegroundColor Red
          }
        }
        
        # 测试发送验证码功能
        Write-Host "`n测试发送验证码功能"
        try {
          # 启动 ChromeDriver
          $driverPath = "bin\Release\net6.0-windows\chromedriver.exe"
          if (Test-Path $driverPath) {
            Write-Host "ChromeDriver 存在，开始测试发送验证码功能"
            
            # 创建测试目录
            $testDir = "SendCodeTest"
            New-Item -ItemType Directory -Path $testDir -Force
            
            # 复制必要文件
            Copy-Item $driverPath -Destination $testDir
            Copy-Item "bin\Release\net6.0-windows\TelegramAutomation.dll" -Destination $testDir
            
            # 测试发送验证码
            $testPhone = "+1234567890"
            Write-Host "测试发送验证码到: $testPhone"
            
            # 模拟点击发送验证码按钮
            Add-Type -AssemblyName System.Windows.Forms
            $button = New-Object System.Windows.Forms.Button
            $button.Text = "发送验证码"
            
            # 创建事件处理
            $clicked = $false
            $button.Add_Click({
              $clicked = $true
              Write-Host "验证码发送按钮点击成功" -ForegroundColor Green
            })
            
            # 模拟点击
            $button.PerformClick()
            
            if ($clicked) {
              Write-Host "发送验证码功能测试成功" -ForegroundColor Green
            } else {
              Write-Host "发送验证码功能测试失败" -ForegroundColor Red
              exit 1
            }
            
            # 清理
            Remove-Item -Path $testDir -Recurse -Force
          } else {
            Write-Host "ChromeDriver 不存在，跳过发送验证码测试" -ForegroundColor Yellow
          }
        } catch {
          Write-Host "发送验证码测试失败: $_" -ForegroundColor Red
          exit 1
        }
        
        # 测试验证码输入
        Write-Host "`n测试验证码输入功能"
        $testCodes = @(
          "123456",
          "000000",
          "999999"
        )
        
        foreach ($code in $testCodes) {
          Write-Host "测试验证码: $code"
          try {
            # 使用 PowerShell 的 Out-File 来测试输入
            $testFile = "code_input_test.txt"
            $code | Out-File -FilePath $testFile
            
            # 读取并验证
            $content = Get-Content -Path $testFile -Raw
            $content = $content.TrimEnd()  # 移除末尾的换行符
            
            if ($content -eq $code) {
              Write-Host "验证码输入测试成功: $code" -ForegroundColor Green
            } else {
              Write-Host "验证码输入测试失败: 期望 '$code', 实际 '$content'" -ForegroundColor Red
              Write-Host "长度对比: 期望 $($code.Length), 实际 $($content.Length)" -ForegroundColor Yellow
            }
            
            # 清理
            Remove-Item $testFile -ErrorAction SilentlyContinue
          } catch {
            Write-Host "验证码输入测试出错: $_" -ForegroundColor Red
          }
        }
        
        Write-Host "`n登录模块测试完成"
        
        # 检查是否有任何测试失败
        if ($LASTEXITCODE -ne 0) {
          Write-Error "登录模块测试失败"
          exit 1
        }

    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true
      
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/Release/net6.0-windows/win-x64/publish/TelegramAutomation.exe
          LICENSE
          README.md
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}