name: Build and Release

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: write

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Install dependencies
      run: dotnet restore
        
    - name: Run tests
      run: dotnet test --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: test
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Install dependencies
      run: dotnet restore
        
    - name: Build
      run: |
        dotnet build --configuration Release `
          /p:Version=${{ github.ref_name }} `
          /p:AssemblyVersion=${{ github.ref_name }} `
          /p:FileVersion=${{ github.ref_name }}
      
    - name: Publish
      run: |
        dotnet publish --configuration Release `
          --runtime win-x64 `
          --self-contained true `
          --output ./publish `
          /p:PublishSingleFile=true `
          /p:IncludeNativeLibrariesForSelfExtract=true `
          /p:EnableCompressionInSingleFile=true `
          /p:DebugType=None `
          /p:DebugSymbols=false
      
    - name: Run Integration Tests
      run: dotnet test ./tests/TelegramAutomation.IntegrationTests --configuration Release
      
    - name: Package Release
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path release -Force
        Copy-Item "publish\TelegramAutomation.exe" -Destination "release\"
        Copy-Item "nlog.config" -Destination "release\"
        Copy-Item "README.md" -Destination "release\"
        Copy-Item "LICENSE" -Destination "release\"
        Copy-Item "CHANGELOG.md" -Destination "release\"
        Compress-Archive -Path "release\*" -DestinationPath "TelegramAutomation.zip" -Force
      
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: TelegramAutomation.zip
        draft: false
        prerelease: false
        body_path: CHANGELOG.md
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TelegramAutomation
        path: release/