name: Build and Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: List Directory
      shell: pwsh
      run: |
        Get-ChildItem -Path . -Recurse | Select-Object FullName
        
    - name: Clean
      run: dotnet clean
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        echo "Building solution..."
        dotnet build `
          --configuration Release `
          --no-restore `
          --verbosity detailed
      
    - name: Package
      run: |
        echo "Publishing application..."
        dotnet publish `
          -c Release `
          -r win-x64 `
          --self-contained true `
          /p:PublishSingleFile=true `
          /p:IncludeNativeLibrariesForSelfExtract=true `
          /p:EnableCompressionInSingleFile=true `
          /p:DebugType=None `
          /p:DebugSymbols=false `
          -o publish `
          --verbosity detailed

    - name: Create Archive
      shell: pwsh
      run: |
        echo "Creating release archive..."
        if (!(Test-Path publish)) {
            throw "Publish directory not found!"
        }
        Copy-Item appsettings.json publish/
        Copy-Item nlog.config publish/
        Copy-Item -Path selenium-manager -Destination publish/selenium-manager -Recurse -ErrorAction SilentlyContinue
        Remove-Item publish/*.pdb -Force -ErrorAction SilentlyContinue
        Get-ChildItem -Path publish -Recurse
        Compress-Archive -Path publish/* -DestinationPath TelegramAutomation.zip -Verbose

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          TelegramAutomation.zip
        draft: false
        prerelease: false